# For SMP Project
version: "3.8"

services:
  redis:
    image: redis:6.0.9-alpine
    container_name: redis
    restart: always
    volumes:
      - ./data/redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ./data/redis/users.acl:/usr/local/etc/redis/users.acl
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      timeout: 3s
      retries: 3
    ports:
      - target: 6379
        published: 6379
        protocol: tcp
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      - smp-network
networks:
  smp-network:
    driver: bridge